[project]
name = "fifa-20-classification"
version = "0.1.0"
description = "FIFA 20 player position classification using skill attributes and machine learning models"
readme = "README.md"
authors = [
    { name = "Ogwang G. Gideon", email = "radigidi@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "joblib>=1.6.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[tool.uv]
package = false
